export default [
{name: "Abingdon-on-Thames", county: "Oxfordshire", type: "town"},
{name: "Accrington", county: "Lancashire", type: "borough"},
{name: "Acle", county: "Norfolk", type: "market charter"},
{name: "Acton", county: "Greater London", type: "borough"},
{name: "Adlington", county: "Lancashire", type: "town"},
{name: "Alcester", county: "Warwickshire", type: "town"},
{name: "Aldeburgh", county: "Suffolk", type: "town"},
{name: "Aldershot", county: "Hampshire", type: "borough"},
{name: "Alford", county: "Lincolnshire", type: "town"},
{name: "Alfreton", county: "Derbyshire", type: "town"},
{name: "Alnwick", county: "Northumberland", type: "town"},
{name: "Alsager", county: "Cheshire", type: "town"},
{name: "Alston", county: "Cumbria", type: "market charter"},
{name: "Alton", county: "Hampshire", type: "town"},
{name: "Altrincham", county: "Greater Manchester", type: "borough"},
{name: "Amble", county: "Northumberland", type: "town"},
{name: "Ambleside", county: "Cumbria", type: "market charter"},
{name: "Amersham", county: "Buckinghamshire", type: "town"},
{name: "Amesbury", county: "Wiltshire", type: "town"},
{name: "Ampthill", county: "Bedfordshire", type: "town"},
{name: "Andover", county: "Hampshire", type: "borough"},
{name: "Appleby-in-Westmorland", county: "Cumbria", type: "town"},
{name: "Arlesey", county: "Bedfordshire", type: "town"},
{name: "Arundel", county: "West Sussex", type: "town"},
{name: "Ashbourne", county: "Derbyshire", type: "town"},
{name: "Ashburton", county: "Devon", type: "town"},
{name: "Ashby-de-la-Zouch", county: "Leicestershire", type: "town"},
{name: "Ashford", county: "Kent", type: "market charter"},
{name: "Ashington", county: "Northumberland", type: "town"},
{name: "Ashton-under-Lyne", county: "Greater Manchester", type: "borough"},
{name: "Askern", county: "South Yorkshire", type: "town"},
{name: "Atherstone", county: "Warwickshire", type: "town"},
{name: "Attleborough", county: "Norfolk", type: "town"},
{name: "Axbridge", county: "Somerset", type: "town"},
{name: "Axminster", county: "Devon", type: "town"},
{name: "Aylesbury", county: "Buckinghamshire", type: "town"},
{name: "Aylsham", county: "Norfolk", type: "town "},
{name: "Bacup", county: "Lancashire", type: "borough"},
{name: "Bakewell", county: "Derbyshire", type: "town"},
{name: "Bampton", county: "Devon", type: "town"},
{name: "Banbury", county: "Oxfordshire", type: "town"},
{name: "Barking", county: "Greater London", type: "borough"},
{name: "Barnard Castle", county: "Durham", type: "town"},
{name: "Barnes", county: "Greater London", type: "borough"},
{name: "Barnet", county: "Greater London", type: "market charter"},
{name: "Barnoldswick", county: "Lancashire", type: "town"},
{name: "Barnsley", county: "South Yorkshire", type: "borough"},
{name: "Barnstaple", county: "Devon", type: "town"},
{name: "Barrow-in-Furness", county: "Cumbria", type: "borough"},
{name: "Barton-upon-Humber", county: "Lincolnshire", type: "town"},
{name: "Basingstoke", county: "Hampshire", type: "borough"},
{name: "Batley", county: "West Yorkshire", type: "borough"},
{name: "Battle", county: "East Sussex", type: "town"},
{name: "Bawtry", county: "South Yorkshire", type: "town"},
{name: "Beaconsfield", county: "Buckinghamshire", type: "town"},
{name: "Beaminster", county: "Dorset", type: "town"},
{name: "Bebington", county: "Merseyside", type: "borough"},
{name: "Beccles", county: "Suffolk", type: "town"},
{name: "Beckenham", county: "Greater London", type: "borough"},
{name: "Bedale", county: "North Yorkshire", type: "town"},
{name: "Bedford", county: "Bedfordshire", type: "borough"},
{name: "Bedworth", county: "Warwickshire", type: "market charter"},
{name: "Belper", county: "Derbyshire", type: "town"},
{name: "Bentham", county: "North Yorkshire", type: "town"},
{name: "Berkeley", county: "Gloucestershire", type: "town"},
{name: "Berkhamsted", county: "Hertfordshire", type: "town"},
{name: "Berwick-upon-Tweed", county: "Northumberland", type: "town"},
{name: "Beverley", county: "East Riding of Yorkshire", type: "town"},
{name: "Bewdley", county: "Worcestershire", type: "town"},
{name: "Bexhill-on-Sea", county: "East Sussex", type: "charter trustees"},
{name: "Bexley", county: "Greater London", type: "borough"},
{name: "Bicester", county: "Oxfordshire", type: "town"},
{name: "Biddulph", county: "Staffordshire", type: "town"},
{name: "Bideford", county: "Devon", type: "town"},
{name: "Biggleswade", county: "Bedfordshire", type: "town"},
{name: "Billericay", county: "Essex", type: "town"},
{name: "Billingham", county: "Durham", type: "town"},
{name: "Bilston", county: "West Midlands", type: "borough"},
{name: "Bingham", county: "Nottinghamshire", type: "town"},
{name: "Bingley", county: "West Yorkshire", type: "market charter"},
{name: "Birchwood", county: "Cheshire", type: "town"},
{name: "Birkenhead", county: "Merseyside", type: "borough"},
{name: "Bishop Auckland", county: "Durham", type: "town"},
{name: "Bishop's Castle", county: "Shropshire", type: "town"},
{name: "Bishop's Stortford", county: "Hertfordshire", type: "town"},
{name: "Bishop's Waltham", county: "Hampshire", type: "market charter"},
{name: "Blackburn", county: "Lancashire", type: "borough"},
{name: "Blackpool", county: "Lancashire", type: "borough"},
{name: "Blackrod", county: "Greater Manchester", type: "town"},
{name: "Blackwater and Hawley", county: "Hampshire", type: "town"},
{name: "Blandford Forum", county: "Dorset", type: "town"},
{name: "Bletchley and Fenny Stratford", county: "Buckinghamshire", type: "town"},
{name: "Blyth", county: "Northumberland", type: "town"},
{name: "Bodmin", county: "Cornwall", type: "town"},
{name: "Bognor Regis", county: "West Sussex", type: "town"},
{name: "Bollington", county: "Cheshire", type: "town"},
{name: "Bolsover", county: "Derbyshire", type: "town"},
{name: "Bolton", county: "Greater Manchester", type: "borough"},
{name: "Bootle", county: "Merseyside", type: "borough"},
{name: "Bordon", county: "Hampshire", type: "town"},
{name: "Boroughbridge", county: "North Yorkshire", type: "town"},
{name: "Boston", county: "Lincolnshire", type: "town"},
{name: "Bottesford", county: "Lincolnshire", type: "town"},
{name: "Bourne", county: "Lincolnshire", type: "town"},
{name: "Bournemouth", county: "Dorset", type: "borough"},
{name: "Bovey Tracey", county: "Devon", type: "town"},
{name: "Brackley", county: "Northamptonshire", type: "town"},
{name: "Bradford-on-Avon", county: "Wiltshire", type: "town"},
{name: "Brading", county: "Isle of Wight", type: "town"},
{name: "Bradley Stoke", county: "Gloucestershire", type: "town"},
{name: "Bradninch", county: "Devon", type: "town"},
{name: "Braintree", county: "Essex", type: "market charter"},
{name: "Brampton", county: "Cumbria", type: "market charter (1252)"},
{name: "Brandon", county: "Suffolk", type: "town"},
{name: "Braunstone Town", county: "Leicestershire", type: "town"},
{name: "Brentford", county: "Greater London", type: "market charter"},
{name: "Brentwood", county: "Essex", type: "market charter"},
{name: "Brewood", county: "Staffordshire", type: "market charter"},
{name: "Bridgnorth", county: "Shropshire", type: "town"},
{name: "Bridgwater", county: "Somerset", type: "town"},
{name: "Bridlington", county: "East Riding of Yorkshire", type: "town"},
{name: "Bridport", county: "Dorset", type: "town"},
{name: "Brierfield", county: "Lancashire", type: "town"},
{name: "Brierley", county: "South Yorkshire", type: "town"},
{name: "Brigg", county: "Lincolnshire", type: "town"},
{name: "Brighouse", county: "West Yorkshire", type: "borough"},
{name: "Brightlingsea", county: "Essex", type: "town"},
{name: "Brixham", county: "Devon", type: "town"},
{name: "Broadstairs and St Peter's", county: "Kent", type: "town"},
{name: "Bromborough", county: "Merseyside", type: "market charter"},
{name: "Bromley", county: "Greater London", type: "borough"},
{name: "Bromsgrove", county: "Worcestershire", type: "market charter"},
{name: "Bromyard", county: "Herefordshire", type: "town"},
{name: "Broseley", county: "Shropshire", type: "town"},
{name: "Brough", county: "East Riding of Yorkshire", type: "town"},
{name: "Broughton", county: "Lincolnshire", type: "town"},
{name: "Broughton-in-Furness", county: "Cumbria", type: "market charter"},
{name: "Bruton", county: "Somerset", type: "town"},
{name: "Buckfastleigh", county: "Devon", type: "town"},
{name: "Buckingham", county: "Buckinghamshire", type: "town"},
{name: "Bude-Stratton", county: "Cornwall", type: "town"},
{name: "Budleigh Salterton", county: "Devon", type: "town"},
{name: "Bulwell", county: "Nottinghamshire", type: "market charter"},
{name: "Bungay", county: "Suffolk", type: "town"},
{name: "Buntingford", county: "Hertfordshire", type: "town"},
{name: "Burford", county: "Oxfordshire", type: "town"},
{name: "Burgess Hill", county: "West Sussex", type: "town"},
{name: "Burgh-le-Marsh", county: "Lincolnshire", type: "town"},
{name: "Burnham-on-Crouch", county: "Essex", type: "town"},
{name: "Burnham-on-Sea", county: "Somerset", type: "town"},
{name: "Burnley", county: "Lancashire", type: "borough"},
{name: "Burntwood", county: "Staffordshire", type: "town"},
{name: "Burslem", county: "Staffordshire", type: "town"},
{name: "Burton Latimer", county: "Northamptonshire", type: "town"},
{name: "Burton upon Trent", county: "Staffordshire", type: "town"},
{name: "Bury", county: "Greater Manchester", type: "borough"},
{name: "Bury St Edmunds", county: "Suffolk", type: "town"},
{name: "Bushey", county: "Hertfordshire", type: "market charter"},
{name: "Buxton", county: "Derbyshire", type: "borough "},
{name: "Caistor", county: "Lincolnshire", type: "town"},
{name: "Callington", county: "Cornwall", type: "town"},
{name: "Calne", county: "Wiltshire", type: "town"},
{name: "Camborne", county: "Cornwall", type: "town"},
{name: "Camelford", county: "Cornwall", type: "town"},
{name: "Cannock", county: "Staffordshire", type: "market charter"},
{name: "Canvey Island", county: "Essex", type: "town"},
{name: "Carnforth", county: "Lancashire", type: "town"},
{name: "Carlton Colville", county: "Suffolk", type: "town"},
{name: "Carshalton", county: "Greater London", type: "Borough"},
{name: "Carterton", county: "Oxfordshire", type: "town"},
{name: "Castle Cary", county: "Somerset", type: "town"},
{name: "Castleford", county: "West Yorkshire", type: "borough"},
{name: "Chagford", county: "Devon", type: "stannary charter"},
{name: "Chapel-en-le-Frith", county: "Derbyshire", type: "market charter"},
{name: "Chard", county: "Somerset", type: "town"},
{name: "Charlbury", county: "Oxfordshire", type: "town"},
{name: "Chatham", county: "Kent", type: "borough"},
{name: "Chatteris", county: "Cambridgeshire", type: "town"},
{name: "Cheadle", county: "Staffordshire", type: "town"},
{name: "Cheltenham", county: "Gloucestershire", type: "borough"},
{name: "Chertsey", county: "Surrey", type: "market charter"},
{name: "Chesham", county: "Buckinghamshire", type: "town"},
{name: "Cheshunt", county: "Hertfordshire", type: "market charter"},
{name: "Chesterfield", county: "Derbyshire", type: "borough"},
{name: "Chester-le-Street", county: "Durham", type: "market charter"},
{name: "Chickerell", county: "Dorset", type: "town"},
{name: "Chilton", county: "County Durham", type: "town"},
{name: "Chingford", county: "Greater London", type: "borough"},
{name: "Chippenham", county: "Wiltshire", type: "town"},
{name: "Chipping Campden", county: "Gloucestershire", type: "town"},
{name: "Chipping Norton", county: "Oxfordshire", type: "town"},
{name: "Chipping Sodbury", county: "Gloucestershire", type: "town"},
{name: "Chiswick", county: "Greater London", type: "borough"},
{name: "Chorley", county: "Lancashire", type: "borough"},
{name: "Chorleywood", county: "Hertfordshire", type: "town"},
{name: "Christchurch", county: "Dorset", type: "borough"},
{name: "Chudleigh", county: "Devon", type: "town"},
{name: "Chulmleigh", county: "Devon", type: "market charter"},
{name: "Church Stretton", county: "Shropshire", type: "town"},
{name: "Cinderford", county: "Gloucestershire", type: "town"},
{name: "Cirencester", county: "Gloucestershire", type: "town"},
{name: "Clare", county: "Suffolk", type: "market charter"},
{name: "Clay Cross", county: "Derbyshire", type: "town"},
{name: "Cleator Moor", county: "Cumbria", type: "town"},
{name: "Cleckheaton", county: "West Yorkshire", type: "market charter"},
{name: "Cleethorpes", county: "Lincolnshire", type: "charter trustees"},
{name: "Cleobury Mortimer", county: "Shropshire", type: "market charter"},
{name: "Clevedon", county: "Somerset", type: "town"},
{name: "Clitheroe", county: "Lancashire", type: "town"},
{name: "Clun", county: "Shropshire", type: "town"},
{name: "Coalville", county: "Leicestershire", type: "town"},
{name: "Cockermouth", county: "Cumbria", type: "town"},
{name: "Coggeshall", county: "Essex", type: "market charter"},
{name: "Colburn", county: "North Yorkshire", type: "town"},
{name: "Colchester", county: "Essex", type: "borough"},
{name: "Coleford", county: "Gloucestershire", type: "town"},
{name: "Coleshill", county: "Warwickshire", type: "town"},
{name: "Colne", county: "Lancashire", type: "town"},
{name: "Colyton", county: "Devon", type: "market charter"},
{name: "Congleton", county: "Cheshire", type: "town"},
{name: "Conisbrough", county: "South Yorkshire", type: "market charter"},
{name: "Corbridge", county: "Northumberland", type: "market charter"},
{name: "Corby", county: "Northamptonshire", type: "market charter"},
{name: "Corringham", county: "Essex", type: "market charter"},
{name: "Corsham", county: "Wiltshire", type: "town"},
{name: "Cosham", county: "Hampshire", type: "town"},
{name: "Cotgrave", county: "Nottinghamshire", type: "town"},
{name: "Cowes", county: "Isle of Wight", type: "town"},
{name: "Coulsdon", county: "Greater London", type: "Municipal Borough"},
{name: "Cramlington", county: "Northumberland", type: "town"},
{name: "Cranbrook", county: "Kent", type: "market charter"},
{name: "Craven Arms", county: "Shropshire", type: "town"},
{name: "Crawley", county: "West Sussex", type: "market charter"},
{name: "Crediton", county: "Devon", type: "town"},
{name: "Crewe", county: "Cheshire", type: "charter trustees"},
{name: "Crewkerne", county: "Somerset", type: "town"},
{name: "Cricklade", county: "Wiltshire", type: "town"},
{name: "Cromer", county: "Norfolk", type: "town"},
{name: "Crook", county: "County Durham", type: "market charter"},
{name: "Crosby", county: "Merseyside", type: "borough"},
{name: "Crowborough", county: "East Sussex", type: "town"},
{name: "Croydon", county: "Greater London", type: "borough"},
{name: "Crowland", county: "Lincolnshire", type: "market charter"},
{name: "Crowle", county: "Lincolnshire", type: "town"},
{name: "Cullompton", county: "Devon", type: "town "},
{name: "Dagenham", county: "Greater London", type: "borough"},
{name: "Dalton-in-Furness", county: "Cumbria", type: "Market Charter[1]"},
{name: "Darley Dale", county: "Derbyshire", type: "town"},
{name: "Darlington", county: "Durham", type: "borough"},
{name: "Dartford", county: "Kent", type: "town"},
{name: "Dartmouth", county: "Devon", type: "town"},
{name: "Darwen", county: "Lancashire", type: "town"},
{name: "Daventry", county: "Northamptonshire", type: "town"},
{name: "Dawley", county: "Shropshire", type: "town"},
{name: "Dawlish", county: "Devon", type: "town"},
{name: "Deal", county: "Kent", type: "town"},
{name: "Denholme", county: "West Yorkshire", type: "town"},
{name: "Dereham", county: "Norfolk", type: "town"},
{name: "Desborough", county: "Northamptonshire", type: "town"},
{name: "Devizes", county: "Wiltshire", type: "town"},
{name: "Dewsbury", county: "West Yorkshire", type: "borough"},
{name: "Didcot", county: "Oxfordshire", type: "town"},
{name: "Dinnington St John's", county: "South Yorkshire", type: "town"},
{name: "Diss", county: "Norfolk", type: "town"},
{name: "Doncaster", county: "South Yorkshire", type: "borough"},
{name: "Dorchester", county: "Dorset", type: "town"},
{name: "Dorking", county: "Surrey", type: "market charter"},
{name: "Dover", county: "Kent", type: "town"},
{name: "Dovercourt", county: "Essex", type: "market charter"},
{name: "Downham Market", county: "Norfolk", type: "town"},
{name: "Driffield", county: "East Riding of Yorkshire", type: "town"},
{name: "Droitwich Spa", county: "Worcestershire", type: "town"},
{name: "Dronfield", county: "Derbyshire", type: "town"},
{name: "Dudley", county: "West Midlands", type: "borough"},
{name: "Dukinfield", county: "Greater Manchester", type: "borough"},
{name: "Dulverton", county: "Somerset", type: "town"},
{name: "Dunstable", county: "Bedfordshire", type: "town"},
{name: "Dunwich", county: "Suffolk", type: "market charter"},
{name: "Dursley", county: "Gloucestershire", type: "town "},
{name: "Ealing", county: "Greater London", type: "borough"},
{name: "Earby", county: "Lancashire", type: "town"},
{name: "Earl Shilton", county: "Leicestershire", type: "town"},
{name: "Earley", county: "Berkshire", type: "town"},
{name: "Easingwold", county: "North Yorkshire", type: "town"},
{name: "East Cowes", county: "Isle of Wight", type: "town"},
{name: "East Grinstead", county: "West Sussex", type: "town"},
{name: "East Ham", county: "Greater London", type: "borough"},
{name: "Eastbourne", county: "East Sussex", type: "borough"},
{name: "Eastleigh", county: "Hampshire", type: "borough"},
{name: "East Retford", county: "Nottinghamshire", type: "charter trustees"},
{name: "Eastwood", county: "Nottinghamshire", type: "town"},
{name: "Eccles", county: "Greater Manchester", type: "borough"},
{name: "Eccleshall", county: "Staffordshire", type: "market charter"},
{name: "Edenbridge", county: "Kent", type: "town"},
{name: "Edgware", county: "Greater London", type: "market charter"},
{name: "Edmonton", county: "Greater London", type: "borough"},
{name: "Egremont", county: "Cumbria", type: "town"},
{name: "Elland", county: "West Yorkshire", type: "market charter"},
{name: "Ellesmere", county: "Shropshire", type: "town"},
{name: "Ellesmere Port", county: "Cheshire", type: "charter trustees"},
{name: "Elstree and Borehamwood", county: "Hertfordshire", type: "town"},
{name: "Emsworth", county: "Hampshire", type: "market charter"},
{name: "Enfield", county: "Greater London", type: "borough"},
{name: "Epping", county: "Essex", type: "town"},
{name: "Epsom and Ewell", county: "Surrey", type: "borough from 1937[2]"},
{name: "Epworth", county: "Lincolnshire", type: "town"},
{name: "Erith", county: "Greater London", type: "borough"},
{name: "Eton", county: "Berkshire", type: "town"},
{name: "Evesham", county: "Worcestershire", type: "town"},
{name: "Exmouth", county: "Devon", type: "town"},
{name: "Eye", county: "Suffolk", type: "town"},
{name: "Fairford", county: "Gloucestershire", type: "town"},
{name: "Fakenham", county: "Norfolk", type: "town"},
{name: "Falmouth", county: "Cornwall", type: "town"},
{name: "Fareham", county: "Hampshire", type: "market charter"},
{name: "Faringdon", county: "Oxfordshire", type: "town"},
{name: "Farnborough", county: "Hampshire", type: "town"},
{name: "Farnham", county: "Surrey", type: "town"},
{name: "Faversham", county: "Kent", type: "town"},
{name: "Fazeley", county: "Staffordshire", type: "town"},
{name: "Featherstone", county: "West Yorkshire", type: "town"},
{name: "Felixstowe", county: "Suffolk", type: "town"},
{name: "Ferndown", county: "Dorset", type: "town"},
{name: "Ferryhill", county: "Durham", type: "town"},
{name: "Filey", county: "North Yorkshire", type: "town"},
{name: "Filton", county: "Gloucestershire", type: "town"},
{name: "Finchley", county: "Greater London", type: "borough"},
{name: "Fleet", county: "Hampshire", type: "town"},
{name: "Fleetwood", county: "Lancashire", type: "borough"},
{name: "Flitwick", county: "Bedfordshire", type: "town"},
{name: "Folkestone", county: "Kent", type: "town"},
{name: "Fordbridge", county: "West Midlands", type: "town"},
{name: "Fordingbridge", county: "Hampshire", type: "town"},
{name: "Fordwich", county: "Kent", type: "town"},
{name: "Fowey", county: "Cornwall", type: "town"},
{name: "Framlingham", county: "Suffolk", type: "town"},
{name: "Frinton and Walton", county: "Essex", type: "town"},
{name: "Frodsham", county: "Cheshire", type: "town"},
{name: "Frome", county: "Somerset", type: "town"},
{name: "Gainsborough", county: "Lincolnshire", type: "town"},
{name: "Garstang", county: "Lancashire", type: "town"},
{name: "Gateshead", county: "Tyne and Wear", type: "borough"},
{name: "Gillingham", county: "Dorset", type: "town"},
{name: "Gillingham", county: "Kent", type: "borough"},
{name: "Glastonbury", county: "Somerset", type: "town"},
{name: "Glossop", county: "Derbyshire", type: "borough"},
{name: "Godalming", county: "Surrey", type: "town"},
{name: "Godmanchester", county: "Cambridgeshire", type: "town"},
{name: "Goole", county: "East Riding of Yorkshire", type: "town"},
{name: "Gorleston-on-Sea", county: "Norfolk", type: "market charter"},
{name: "Gosport", county: "Hampshire", type: "borough"},
{name: "Grange-over-Sands", county: "Cumbria", type: "town"},
{name: "Grantham", county: "Lincolnshire", type: "charter trustees"},
{name: "Grassington", county: "North Yorkshire", type: "market charter"},
{name: "Gravesend", county: "Kent", type: "borough"},
{name: "Grays", county: "Essex", type: "market charter"},
{name: "Great Dunmow", county: "Essex", type: "town"},
{name: "Great Torrington", county: "Devon", type: "town"},
{name: "Great Yarmouth", county: "Norfolk", type: "borough"},
{name: "Greater Willington", county: "Durham", type: "town"},
{name: "Grimsby", county: "Lincolnshire", type: "charter trustees"},
{name: "Guildford", county: "Surrey", type: "borough"},
{name: "Guisborough", county: "North Yorkshire", type: "town"},
{name: "Hadleigh", county: "Suffolk", type: "town"},
{name: "Hailsham", county: "East Sussex", type: "town"},
{name: "Halesowen", county: "West Midlands", type: "borough"},
{name: "Halesworth", county: "Suffolk", type: "town"},
{name: "Halewood", county: "Merseyside", type: "town"},
{name: "Halifax", county: "West Yorkshire", type: "borough"},
{name: "Halstead", county: "Essex", type: "town"},
{name: "Haltwhistle", county: "Northumberland", type: "town"},
{name: "Redenhall with Harleston", county: "Norfolk", type: "town"},
{name: "Harlow", county: "Essex", type: "market charter"},
{name: "Harpenden", county: "Hertfordshire", type: "town"},
{name: "Harrogate", county: "North Yorkshire", type: "borough"},
{name: "Harrow", county: "Greater London", type: "borough"},
{name: "Hartland", county: "Devon", type: "market charter"},
{name: "Hartlepool", county: "Durham", type: "borough"},
{name: "Harwich", county: "Essex", type: "town"},
{name: "Harworth and Bircotes", county: "Nottinghamshire", type: "town"},
{name: "Haslemere", county: "Surrey", type: "town"},
{name: "Haslingden", county: "Lancashire", type: "borough"},
{name: "Hastings", county: "East Sussex", type: "borough"},
{name: "Hatfield", county: "Hertfordshire", type: "town"},
{name: "Hatfield", county: "South Yorkshire", type: "town"},
{name: "Hatherleigh", county: "Devon", type: "town"},
{name: "Havant", county: "Hampshire", type: "market charter"},
{name: "Haverhill", county: "Suffolk", type: "town"},
{name: "Hawkinge", county: "Kent", type: "town"},
{name: "Haxby", county: "North Yorkshire", type: "town"},
{name: "Hawes", county: "North Yorkshire", type: "market charter"},
{name: "Hayle", county: "Cornwall", type: "town"},
{name: "Haywards Heath", county: "West Sussex", type: "town"},
{name: "Heanor and Loscoe", county: "Derbyshire", type: "town"},
{name: "Heathfield", county: "East Sussex", type: "market charter"},
{name: "Hebden Royd", county: "West Yorkshire", type: "town"},
{name: "Hedge End", county: "Hampshire", type: "town"},
{name: "Hednesford", county: "Staffordshire", type: "town"},
{name: "Hedon", county: "East Riding of Yorkshire", type: "town"},
{name: "Helmsley", county: "North Yorkshire", type: "town"},
{name: "Helston", county: "Cornwall", type: "town"},
{name: "Hemel Hempstead", county: "Hertfordshire", type: "town"},
{name: "Hemsworth", county: "West Yorkshire", type: "town"},
{name: "Hendon", county: "Greater London", type: "borough"},
{name: "Henley-in-Arden", county: "Warwickshire", type: "market charter"},
{name: "Henley-on-Thames", county: "Oxfordshire", type: "town"},
{name: "Hertford", county: "Hertfordshire", type: "town"},
{name: "Hessle", county: "East Riding of Yorkshire", type: "town"},
{name: "Hetton", county: "Tyne and Wear", type: "town"},
{name: "Hexham", county: "Northumberland", type: "town"},
{name: "Heywood", county: "Greater Manchester", type: "borough"},
{name: "Higham Ferrers", county: "Northamptonshire", type: "town"},
{name: "Highbridge", county: "Somerset", type: "market charter"},
{name: "Highworth", county: "Wiltshire", type: "town"},
{name: "High Wycombe", county: "Buckinghamshire", type: "charter trustees"},
{name: "Hinckley", county: "Leicestershire", type: "market charter"},
{name: "Hingham", county: "Norfolk", type: "town"},
{name: "Hitchin", county: "Hertfordshire", type: "market charter"},
{name: "Hoddesdon", county: "Hertfordshire", type: "market charter"},
{name: "Holbeach", county: "Lincolnshire", type: "market charter"},
{name: "Holsworthy", county: "Devon", type: "town"},
{name: "Holt", county: "Norfolk", type: "town"},
{name: "Honiton", county: "Devon", type: "town"},
{name: "Horley", county: "Surrey", type: "town"},
{name: "Horncastle", county: "Lincolnshire", type: "town"},
{name: "Hornsea", county: "East Riding of Yorkshire", type: "town"},
{name: "Hornsey", county: "Greater London", type: "borough"},
{name: "Horsforth", county: "West Yorkshire", type: "town"},
{name: "Horsham", county: "West Sussex", type: "town"},
{name: "Horwich", county: "Greater Manchester", type: "town"},
{name: "Houghton Regis", county: "Bedfordshire", type: "town"},
{name: "Hounslow", county: "Greater London", type: "Borough"},
{name: "Howden", county: "East Riding of Yorkshire", type: "town"},
{name: "Huddersfield", county: "West Yorkshire", type: "borough"},
{name: "Hungerford", county: "Berkshire", type: "town"},
{name: "Hunstanton", county: "Norfolk", type: "town"},
{name: "Huntingdon", county: "Cambridgeshire", type: "town"},
{name: "Hyde", county: "Greater Manchester", type: "borough"},
{name: "Hythe", county: "Kent", type: "town"},
{name: "Ilford", county: "Greater London", type: "borough"},
{name: "Ilfracombe", county: "Devon", type: "town"},
{name: "Ilkeston", county: "Derbyshire", type: "town"},
{name: "Ilkley", county: "West Yorkshire", type: "town"},
{name: "Ilminster", county: "Somerset", type: "town"},
{name: "Immingham", county: "Lincolnshire", type: "town"},
{name: "Ingleby Barwick", county: "North Yorkshire", type: "town"},
{name: "Ipswich", county: "Suffolk", type: "borough"},
{name: "Irthlingborough", county: "Northamptonshire", type: "town"},
{name: "Isleworth", county: "Greater London", type: "borough"},
{name: "Ivybridge", county: "Devon", type: "town "},
{name: "Jarrow", county: "Tyne and Wear", type: "borough"},
{name: "Keighley", county: "West Yorkshire", type: "town"},
{name: "Kempston", county: "Bedfordshire", type: "town"},
{name: "Kendal", county: "Cumbria", type: "town"},
{name: "Kenilworth", county: "Warwickshire", type: "town"},
{name: "Kesgrave", county: "Suffolk", type: "town"},
{name: "Keswick", county: "Cumbria", type: "town"},
{name: "Kettering", county: "Northamptonshire", type: "borough"},
{name: "Keynsham", county: "Somerset", type: "town"},
{name: "Kidderminster", county: "Worcestershire", type: "charter trustees"},
{name: "Kidsgrove", county: "Staffordshire", type: "town"},
{name: "Kimberley", county: "Nottinghamshire", type: "town"},
{name: "King's Lynn", county: "Norfolk", type: "borough"},
{name: "Kingsbridge", county: "Devon", type: "town"},
{name: "Kingsteignton", county: "Devon", type: "town"},
{name: "Kingston-upon-Thames", county: "Greater London", type: "borough"},
{name: "Kington", county: "Herefordshire", type: "town"},
{name: "Kirkby-in-Ashfield", county: "Nottinghamshire", type: "market charter"},
{name: "Kirkby Lonsdale", county: "Cumbria", type: "town"},
{name: "Kirkby Stephen", county: "Cumbria", type: "town"},
{name: "Kirkbymoorside", county: "North Yorkshire", type: "town"},
{name: "Kirkham", county: "Lancashire", type: "town"},
{name: "Kirton-in-Lindsey", county: "Lincolnshire", type: "town"},
{name: "Knaresborough", county: "North Yorkshire", type: "town"},
{name: "Knutsford", county: "Cheshire", type: "town"},
{name: "Langport", county: "Somerset", type: "town"},
{name: "Launceston", county: "Cornwall", type: "town"},
{name: "Leatherhead", county: "Surrey", type: "market charter"},
{name: "Lechlade", county: "Gloucestershire", type: "town"},
{name: "Ledbury", county: "Herefordshire", type: "town"},
{name: "Leek", county: "Staffordshire", type: "town"},
{name: "Leigh", county: "Greater Manchester", type: "borough"},
{name: "Leighton-Linslade", county: "Bedfordshire", type: "town"},
{name: "Leigh-on-Sea", county: "Essex", type: "town"},
{name: "Leiston", county: "Suffolk", type: "town"},
{name: "Leominster", county: "Herefordshire", type: "town"},
{name: "Letchworth Garden City", county: "Hertfordshire", type: "town"},
{name: "Lewes", county: "East Sussex", type: "town"},
{name: "Leyburn", county: "North Yorkshire", type: "town"},
{name: "Leyland", county: "Lancashire", type: "town"},
{name: "Leyton", county: "Greater London", type: "borough"},
{name: "Liskeard", county: "Cornwall", type: "town"},
{name: "Littlehampton", county: "West Sussex", type: "town"},
{name: "Loddon", county: "Norfolk", type: "market charter"},
{name: "Loftus", county: "North Yorkshire", type: "town"},
{name: "Long Sutton", county: "Lincolnshire", type: "market charter"},
{name: "Longridge", county: "Lancashire", type: "town"},
{name: "Longtown", county: "Cumbria", type: "market charter"},
{name: "Looe", county: "Cornwall", type: "town"},
{name: "Lostwithiel", county: "Cornwall", type: "town"},
{name: "Loughborough", county: "Leicestershire", type: "borough"},
{name: "Loughton", county: "Essex", type: "town"},
{name: "Louth", county: "Lincolnshire", type: "town"},
{name: "Lowestoft", county: "Suffolk", type: "charter trustees"},
{name: "Ludgershall", county: "Wiltshire", type: "town"},
{name: "Ludlow", county: "Shropshire", type: "town"},
{name: "Luton", county: "Bedfordshire", type: "borough"},
{name: "Lutterworth", county: "Leicestershire", type: "town"},
{name: "Lydd", county: "Kent", type: "town"},
{name: "Lydney", county: "Gloucestershire", type: "town"},
{name: "Lyme Regis", county: "Dorset", type: "town"},
{name: "Lymington", county: "Hampshire", type: "town"},
{name: "Lynton & Lynmouth", county: "Devon", type: "town"},
{name: "Lytchett Minster & Upton", county: "Dorset", type: "town"},
{name: "Lytham St Annes", county: "Lancashire", type: "borough "},
{name: "Mablethorpe and Sutton", county: "Lincolnshire", type: "town"},
{name: "Macclesfield", county: "Cheshire", type: "charter trustees"},
{name: "Madeley", county: "Shropshire", type: "market charter"},
{name: "Maghull", county: "Merseyside", type: "town"},
{name: "Maidenhead", county: "Berkshire", type: "borough"},
{name: "Maidstone", county: "Kent", type: "borough"},
{name: "Maldon", county: "Essex", type: "town"},
{name: "Malmesbury", county: "Wiltshire", type: "town"},
{name: "Maltby", county: "South Yorkshire", type: "town"},
{name: "Malton", county: "North Yorkshire", type: "town"},
{name: "Malvern", county: "Worcestershire", type: "town"},
{name: "Manningtree", county: "Essex", type: "town"},
{name: "Mansfield", county: "Nottinghamshire", type: "charter trustees"},
{name: "Marazion", county: "Cornwall", type: "town"},
{name: "March", county: "Cambridgeshire", type: "town"},
{name: "Margate", county: "Kent", type: "charter trustees"},
{name: "Market Bosworth", county: "Leicestershire", type: "market charter"},
{name: "Market Deeping", county: "Lincolnshire", type: "town"},
{name: "Market Drayton", county: "Shropshire", type: "town"},
{name: "Market Harborough", county: "Leicestershire", type: "market charter"},
{name: "Market Rasen", county: "Lincolnshire", type: "town"},
{name: "Market Weighton", county: "East Riding of Yorkshire", type: "town"},
{name: "Marlborough", county: "Wiltshire", type: "town"},
{name: "Marlow", county: "Buckinghamshire", type: "town"},
{name: "Maryport", county: "Cumbria", type: "town"},
{name: "Masham", county: "North Yorkshire", type: "market charter"},
{name: "Matlock", county: "Derbyshire", type: "town"},
{name: "Medlar-with-Wesham", county: "Lancashire", type: "town"},
{name: "Melksham", county: "Wiltshire", type: "town"},
{name: "Meltham", county: "West Yorkshire", type: "town"},
{name: "Melton Mowbray", county: "Leicestershire", type: "town"},
{name: "Mere", county: "Wiltshire", type: "town"},
{name: "Mexborough", county: "South Yorkshire", type: "market charter"},
{name: "Middleham", county: "North Yorkshire", type: "town"},
{name: "Middlesbrough", county: "North Yorkshire", type: "borough"},
{name: "Middleton", county: "Greater Manchester", type: "borough"},
{name: "Middlewich", county: "Cheshire", type: "town"},
{name: "Midhurst", county: "West Sussex", type: "town"},
{name: "Midsomer Norton", county: "Somerset", type: "market charter"},
{name: "Mildenhall", county: "Suffolk", type: "market charter"},
{name: "Millom", county: "Cumbria", type: "town"},
{name: "Minchinhampton", county: "Gloucestershire", type: "market charter"},
{name: "Minehead", county: "Somerset", type: "town"},
{name: "Minster", county: "Kent", type: "market charter"},
{name: "Mirfield", county: "West Yorkshire", type: "town"},
{name: "Mitcham", county: "Greater London", type: "borough"},
{name: "Mitcheldean", county: "Gloucestershire", type: "market charter"},
{name: "Modbury", county: "Devon", type: "market charter"},
{name: "Morecambe", county: "Lancashire", type: "town"},
{name: "Moretonhampstead", county: "Devon", type: "market charter"},
{name: "Moreton-in-Marsh", county: "Gloucestershire", type: "town"},
{name: "Morley", county: "West Yorkshire", type: "town"},
{name: "Morpeth", county: "Northumberland", type: "borough"},
{name: "Mossley", county: "Greater Manchester", type: "town"},
{name: "Much Wenlock", county: "Shropshire", type: "town "},
{name: "Nailsea", county: "Somerset", type: "town"},
{name: "Nailsworth", county: "Gloucestershire", type: "town"},
{name: "Nantwich", county: "Cheshire", type: "town"},
{name: "Needham Market", county: "Suffolk", type: "town"},
{name: "Nelson", county: "Lancashire", type: "town"},
{name: "Neston", county: "Cheshire", type: "town"},
{name: "New Alresford", county: "Hampshire", type: "town"},
{name: "New Malden", county: "Greater London", type: "borough"},
{name: "New Mills", county: "Derbyshire", type: "town"},
{name: "New Milton", county: "Hampshire", type: "town"},
{name: "New Romney", county: "Kent", type: "town"},
{name: "Newark-on-Trent", county: "Nottinghamshire", type: "town"},
{name: "Newbiggin-by-the-Sea", county: "Northumberland", type: "town"},
{name: "Newbury", county: "Berkshire", type: "town"},
{name: "Newcastle-under-Lyme", county: "Staffordshire", type: "borough"},
{name: "Newent", county: "Gloucestershire", type: "town"},
{name: "Newhaven", county: "East Sussex", type: "town"},
{name: "Newlyn", county: "Cornwall", type: "market charter"},
{name: "Newmarket", county: "Suffolk", type: "town"},
{name: "Newport", county: "Isle of Wight", type: "borough"},
{name: "Newport", county: "Shropshire", type: "town"},
{name: "Newport Pagnell", county: "Buckinghamshire", type: "town"},
{name: "Newquay", county: "Cornwall", type: "town"},
{name: "Newton Abbot", county: "Devon", type: "town"},
{name: "Newton Aycliffe", county: "County Durham", type: "town"},
{name: "Newton-le-Willows", county: "Merseyside", type: "market charter"},
{name: "Normanton", county: "West Yorkshire", type: "town"},
{name: "North Hykeham", county: "Lincolnshire", type: "town"},
{name: "North Petherton", county: "Somerset", type: "town"},
{name: "North Tawton", county: "Devon", type: "town"},
{name: "North Walsham", county: "Norfolk", type: "town"},
{name: "Northallerton", county: "North Yorkshire", type: "town"},
{name: "Northam", county: "Devon", type: "town"},
{name: "Northampton", county: "Northamptonshire", type: "borough"},
{name: "Northfleet", county: "Kent", type: "market charter"},
{name: "Northleach with Eastington", county: "Gloucestershire", type: "town"},
{name: "Northwich", county: "Cheshire", type: "town"},
{name: "Norton-on-Derwent", county: "North Yorkshire", type: "town"},
{name: "Nuneaton", county: "Warwickshire", type: "borough "},
{name: "Oakengates", county: "Shropshire", type: "town"},
{name: "Oakham", county: "Rutland", type: "town"},
{name: "Okehampton", county: "Devon", type: "town"},
{name: "Oldbury", county: "West Midlands", type: "borough"},
{name: "Oldham", county: "Greater Manchester", type: "borough"},
{name: "Ollerton and Boughton", county: "Nottinghamshire", type: "town"},
{name: "Olney", county: "Buckinghamshire", type: "town"},
{name: "Ongar", county: "Essex", type: "town"},
{name: "Orford", county: "Suffolk", type: "market charter"},
{name: "Ormskirk", county: "Lancashire", type: "market charter"},
{name: "Orpington", county: "Greater London", type: "Town"},
{name: "Ossett", county: "West Yorkshire", type: "borough"},
{name: "Oswestry", county: "Shropshire", type: "town"},
{name: "Otley", county: "West Yorkshire", type: "town"},
{name: "Ottery St Mary", county: "Devon", type: "town"},
{name: "Oundle", county: "Northamptonshire", type: "town"},
{name: "Paddock Wood", county: "Kent", type: "town"},
{name: "Padiham", county: "Lancashire", type: "town"},
{name: "Padstow", county: "Cornwall", type: "town"},
{name: "Paignton", county: "Devon", type: "market charter"},
{name: "Painswick", county: "Gloucestershire", type: "market charter"},
{name: "Partington", county: "Greater Manchester", type: "town"},
{name: "Patchway", county: "Gloucestershire", type: "town"},
{name: "Pateley Bridge", county: "North Yorkshire", type: "town"},
{name: "Peacehaven", county: "East Sussex", type: "town"},
{name: "Penistone", county: "South Yorkshire", type: "town"},
{name: "Penkridge", county: "Staffordshire", type: "market charter"},
{name: "Penrith", county: "Cumbria", type: "market charter"},
{name: "Penryn", county: "Cornwall", type: "town"},
{name: "Penwortham", county: "Lancashire", type: "town"},
{name: "Penzance", county: "Cornwall", type: "town"},
{name: "Pershore", county: "Worcestershire", type: "town"},
{name: "Peterlee", county: "Durham", type: "town"},
{name: "Petersfield", county: "Hampshire", type: "town"},
{name: "Petworth", county: "West Sussex", type: "town"},
{name: "Pickering", county: "North Yorkshire", type: "town"},
{name: "Plympton", county: "Devon", type: "market charter"},
{name: "Pocklington", county: "East Riding of Yorkshire", type: "town"},
{name: "Polegate", county: "East Sussex", type: "town"},
{name: "Pontefract", county: "West Yorkshire", type: "borough"},
{name: "Ponteland", county: "Northumberland", type: "town"},
{name: "Poole", county: "Dorset", type: "borough"},
{name: "Porthleven", county: "Cornwall", type: "town"},
{name: "Portishead and North Weston", county: "Somerset", type: "town"},
{name: "Portland", county: "Dorset", type: "town"},
{name: "Potton", county: "Bedfordshire", type: "town"},
{name: "Poynton-with-Worth", county: "Cheshire", type: "town"},
{name: "Preesall", county: "Lancashire", type: "town"},
{name: "Prescot", county: "Merseyside", type: "town"},
{name: "Princes Risborough", county: "Buckinghamshire", type: "town"},
{name: "Prudhoe", county: "Northumberland", type: "town"},
{name: "Pudsey", county: "West Yorkshire", type: "borough"},
{name: "Purley", county: "Greater London", type: "town "},
{name: "Quedgeley", county: "Gloucestershire", type: "town[3]"},
{name: "Queenborough-in-Sheppey", county: "Kent", type: "town"},
{name: "Radstock", county: "Somerset", type: "town"},
{name: "Ramsey", county: "Cambridgeshire", type: "town"},
{name: "Ramsgate", county: "Kent", type: "town"},
{name: "Raunds", county: "Northamptonshire", type: "town"},
{name: "Rawtenstall", county: "Lancashire", type: "borough"},
{name: "Rayleigh", county: "Essex", type: "town"},
{name: "Reading", county: "Berkshire", type: "borough"},
{name: "Redcar", county: "North Yorkshire", type: "borough"},
{name: "Redditch", county: "Worcestershire", type: "town"},
{name: "Redhill", county: "Surrey", type: ""},
{name: "Redruth", county: "Cornwall", type: "town"},
{name: "Reepham", county: "Norfolk", type: "town"},
{name: "Reigate", county: "Surrey", type: "borough"},
{name: "Richmond", county: "Greater London", type: "borough"},
{name: "Richmond", county: "North Yorkshire", type: "town"},
{name: "Ringwood", county: "Hampshire", type: "town"},
{name: "Ripley", county: "Derbyshire", type: "town"},
{name: "Rochdale", county: "Greater Manchester", type: "borough"},
{name: "Rochester", county: "Kent", type: "borough2"},
{name: "Rochford", county: "Essex", type: "market charter"},
{name: "Romford", county: "Greater London", type: "borough"},
{name: "Romsey", county: "Hampshire", type: "town"},
{name: "Ross-on-Wye", county: "Herefordshire", type: "town"},
{name: "Rothbury", county: "Northumberland", type: "market charter"},
{name: "Rotherham", county: "South Yorkshire", type: "borough"},
{name: "Rothwell", county: "Northamptonshire", type: "town"},
{name: "Rothwell", county: "West Yorkshire", type: "market charter"},
{name: "Rowley Regis", county: "West Midlands", type: "borough"},
{name: "Royal Leamington Spa", county: "Warwickshire", type: "town"},
{name: "Royal Tunbridge Wells", county: "Kent", type: "borough"},
{name: "Royal Wootton Bassett", county: "Wiltshire", type: "town"},
{name: "Royston", county: "Hertfordshire", type: "town"},
{name: "Rugby", county: "Warwickshire", type: "borough"},
{name: "Rugeley", county: "Staffordshire", type: "town"},
{name: "Rushden", county: "Northamptonshire", type: "town"},
{name: "Ryde", county: "Isle of Wight", type: "town"},
{name: "Rye", county: "East Sussex", type: "town"},
{name: "Saffron Walden", county: "Essex", type: "town"},
{name: "St Austell", county: "Cornwall", type: "town"},
{name: "St Blaise", county: "Cornwall", type: "town"},
{name: "St Columb Major", county: "Cornwall", type: "town"},
{name: "St Helens", county: "Merseyside", type: "borough"},
{name: "St Ives", county: "Cambridgeshire", type: "town"},
{name: "St Ives", county: "Cornwall", type: "town"},
{name: "St Just-in-Penwith", county: "Cornwall", type: "town"},
{name: "St Mary Cray", county: "Greater London", type: "market charter"},
{name: "St Mawes", county: "Cornwall", type: "market charter"},
{name: "St Neots", county: "Cambridgeshire", type: "town"},
{name: "Salcombe", county: "Devon", type: "town"},
{name: "Sale", county: "Greater Manchester", type: "borough"},
{name: "Saltash", county: "Cornwall", type: "town"},
{name: "Sandbach", county: "Cheshire", type: "town"},
{name: "Sandhurst", county: "Berkshire", type: "town"},
{name: "Sandiacre", county: "Derbyshire", type: "market charter"},
{name: "Sandown", county: "Isle of Wight", type: "town"},
{name: "Sandwich", county: "Kent", type: "town"},
{name: "Sandy", county: "Bedfordshire", type: "town"},
{name: "Sawbridgeworth", county: "Hertfordshire", type: "town"},
{name: "Saxmundham", county: "Suffolk", type: "town"},
{name: "Scarborough", county: "North Yorkshire", type: "borough"},
{name: "Scunthorpe", county: "Lincolnshire", type: "charter trustees"},
{name: "Seaford", county: "East Sussex", type: "town"},
{name: "Seaham", county: "Durham", type: "town"},
{name: "Seaton", county: "Devon", type: "town"},
{name: "Sedbergh", county: "Cumbria", type: "market charter"},
{name: "Sedgefield", county: "County Durham", type: "town"},
{name: "Selby", county: "North Yorkshire", type: "town"},
{name: "Selsey", county: "West Sussex", type: "town"},
{name: "Settle", county: "North Yorkshire", type: "town"},
{name: "Sevenoaks", county: "Kent", type: "town"},
{name: "Shaftesbury", county: "Dorset", type: "town"},
{name: "Shanklin", county: "Isle of Wight", type: "town"},
{name: "Shefford", county: "Bedfordshire", type: "town"},
{name: "Shepshed", county: "Leicestershire", type: "town"},
{name: "Shepton Mallet", county: "Somerset", type: "town"},
{name: "Sherborne", county: "Dorset", type: "town"},
{name: "Sheringham", county: "Norfolk", type: "town"},
{name: "Shifnal", county: "Shropshire", type: "town"},
{name: "Shildon", county: "Durham", type: "town"},
{name: "Shipston-on-Stour", county: "Warwickshire", type: "town"},
{name: "Shirebrook", county: "Derbyshire", type: "town"},
{name: "Shoreham-by-Sea", county: "West Sussex", type: "market charter"},
{name: "Shrewsbury", county: "Shropshire", type: "town"},
{name: "Sidmouth", county: "Devon", type: "town"},
{name: "Silloth", county: "Cumbria", type: "town"},
{name: "Silsden", county: "West Yorkshire", type: "town"},
{name: "Sittingbourne", county: "Kent", type: "town"},
{name: "Skegness", county: "Lincolnshire", type: "town"},
{name: "Skelmersdale", county: "Lancashire", type: "town"},
{name: "Skelton-in-Cleveland", county: "North Yorkshire", type: "market charter"},
{name: "Skipton", county: "North Yorkshire", type: "town"},
{name: "Sleaford", county: "Lincolnshire", type: "town"},
{name: "Slough", county: "Berkshire", type: "borough"},
{name: "Smethwick", county: "West Midlands", type: "borough"},
{name: "Snaith and Cowick", county: "East Riding of Yorkshire", type: "town"},
{name: "Snodland", county: "Kent", type: "town"},
{name: "Soham", county: "Cambridgeshire", type: "town"},
{name: "Solihull", county: "West Midlands", type: "borough"},
{name: "Somerton", county: "Somerset", type: "town"},
{name: "South Brent", county: "Devon", type: "market charter"},
{name: "South Cave", county: "East Riding of Yorkshire", type: "market charter"},
{name: "South Elmsall", county: "West Yorkshire", type: "town"},
{name: "South Kirkby and Moorthorpe", county: "West Yorkshire", type: "town"},
{name: "South Molton", county: "Devon", type: "town"},
{name: "South Shields", county: "Tyne and Wear", type: "borough"},
{name: "South Woodham Ferrers", county: "Essex", type: "town"},
{name: "Southam", county: "Warwickshire", type: "town"},
{name: "Southall", county: "Greater London", type: "borough"},
{name: "Southborough", county: "Kent", type: "town"},
{name: "Southend-on-Sea", county: "Essex", type: "borough"},
{name: "Southgate", county: "Greater London", type: "borough"},
{name: "Southminster", county: "Essex", type: "market charter"},
{name: "Southport", county: "Merseyside", type: "borough"},
{name: "Southsea", county: "Hampshire", type: "town"},
{name: "Southwell", county: "Nottinghamshire", type: "town"},
{name: "Southwick", county: "Hampshire", type: "market charter"},
{name: "Southwold", county: "Suffolk", type: "town"},
{name: "Spalding", county: "Lincolnshire", type: "town"},
{name: "Spennymoor", county: "Durham", type: "town"},
{name: "Spilsby", county: "Lincolnshire", type: "town"},
{name: "Sprowston", county: "Norfolk", type: "town"},
{name: "Stafford", county: "Staffordshire", type: "borough"},
{name: "Staines-upon-Thames", county: "Surrey", type: "market charter"},
{name: "Stainforth", county: "South Yorkshire", type: "town"},
{name: "Stalbridge", county: "Dorset", type: "town"},
{name: "Stalham", county: "Norfolk", type: "market charter"},
{name: "Stalybridge", county: "Greater Manchester", type: "borough"},
{name: "Stamford", county: "Lincolnshire", type: "town"},
{name: "Stanley", county: "Durham", type: "town"},
{name: "Stanhope", county: "Durham", type: "market charter"},
{name: "Stapleford", county: "Nottinghamshire", type: "town"},
{name: "Staveley", county: "Derbyshire", type: "town"},
{name: "Stevenage", county: "Hertfordshire", type: "market charter"},
{name: "Steyning", county: "West Sussex", type: "market charter"},
{name: "Stockport", county: "Greater Manchester", type: "borough"},
{name: "Stocksbridge", county: "South Yorkshire", type: "town"},
{name: "Stockton-on-Tees", county: "Durham/North Yorkshire", county: "borough"},
{name: "Stone", county: "Staffordshire", type: "town"},
{name: "Stonehouse", county: "Gloucestershire", type: "town"},
{name: "Stony Stratford", county: "Buckinghamshire", type: "town"},
{name: "Stotfold", county: "Bedfordshire", type: "town"},
{name: "Stourbridge", county: "West Midlands", type: "borough"},
{name: "Stourport-on-Severn", county: "Worcestershire", type: "town"},
{name: "Stowmarket", county: "Suffolk", type: "town"},
{name: "Stow-on-the-Wold", county: "Gloucestershire", type: "town"},
{name: "Stratford-upon-Avon", county: "Warwickshire", type: "town"},
{name: "Stretford", county: "Greater Manchester", type: "borough"},
{name: "Strood", county: "Kent", type: "market charter"},
{name: "Stroud", county: "Gloucestershire", type: "town"},
{name: "Sturminster Newton", county: "Dorset", type: "town"},
{name: "Sudbury", county: "Suffolk", type: "town"},
{name: "Surbiton", county: "Greater London", type: "borough"},
{name: "Sutton", county: "Greater London", type: "borough"},
{name: "Sutton Coldfield", county: "West Midlands", type: "market charter"},
{name: "Swaffham", county: "Norfolk", type: "town"},
{name: "Swanage", county: "Dorset", type: "town"},
{name: "Swanley", county: "Kent", type: "town"},
{name: "Swanscombe and Greenhithe", county: "Kent", type: "town"},
{name: "Swindon", county: "Wiltshire", type: "borough"},
{name: "Syston", county: "Leicestershire", type: "town "},
{name: "Tadcaster", county: "North Yorkshire", type: "town"},
{name: "Tadley", county: "Hampshire", type: "town"},
{name: "Tamworth", county: "Staffordshire", type: "borough"},
{name: "Taunton", county: "Somerset", type: "borough"},
{name: "Tavistock", county: "Devon", type: "town"},
{name: "Teignmouth", county: "Devon", type: "town"},
{name: "Telscombe", county: "East Sussex", type: "town"},
{name: "Tenbury Wells", county: "Worcestershire", type: "town"},
{name: "Tenterden", county: "Kent", type: "town"},
{name: "Tetbury", county: "Gloucestershire", type: "town"},
{name: "Tewkesbury", county: "Gloucestershire", type: "town"},
{name: "Thame", county: "Oxfordshire", type: "town"},
{name: "Thatcham", county: "Berkshire", type: "town"},
{name: "Thaxted", county: "Essex", type: "market charter"},
{name: "Thetford", county: "Norfolk", type: "town"},
{name: "Thirsk", county: "North Yorkshire", type: "town"},
{name: "Thornaby-on-Tees", county: "North Yorkshire", type: "town"},
{name: "Thornbury", county: "Gloucestershire", type: "town"},
{name: "Thorne", county: "South Yorkshire", type: "town"},
{name: "Thorpe St Andrew", county: "Norfolk", type: "town"},
{name: "Thrapston", county: "Northamptonshire", type: "town"},
{name: "Tickhill", county: "South Yorkshire", type: "town"},
{name: "Tidworth", county: "Wiltshire", type: "town"},
{name: "Tipton", county: "West Midlands", type: "borough"},
{name: "Tiverton", county: "Devon", type: "town"},
{name: "Todmorden", county: "West Yorkshire", type: "town"},
{name: "Tonbridge", county: "Kent", type: "market charter"},
{name: "Topsham", county: "Devon", type: "market charter"},
{name: "Torpoint", county: "Cornwall", type: "town"},
{name: "Torquay", county: "Devon", type: "borough"},
{name: "Totnes", county: "Devon", type: "town"},
{name: "Tottenham", county: "Greater London", type: "borough"},
{name: "Totton and Eling", county: "Hampshire", type: "town"},
{name: "Tow Law", county: "Durham", type: "town"},
{name: "Towcester", county: "Northamptonshire", type: "town"},
{name: "Tring", county: "Hertfordshire", type: "town"},
{name: "Trowbridge", county: "Wiltshire", type: "town"},
{name: "Twickenham", county: "Greater London", type: "borough"},
{name: "Tynemouth", county: "Tyne and Wear", type: "borough"},
{name: "Uckfield", county: "East Sussex", type: "town"},
{name: "Ulverston", county: "Cumbria", type: "town"},
{name: "Uppingham", county: "Rutland", type: "town"},
{name: "Upton-upon-Severn", county: "Worcestershire", type: "town"},
{name: "Uttoxeter", county: "Staffordshire", type: "town"},
{name: "Uxbridge", county: "Greater London", type: "borough"},
{name: "Ventnor", county: "Isle of Wight", type: "town"},
{name: "Verwood", county: "Dorset", type: "town "},
{name: "Wadebridge", county: "Cornwall", type: "town"},
{name: "Wadhurst", county: "East Sussex", type: "market charter"},
{name: "Wainfleet All Saints", county: "Lincolnshire", type: "town"},
{name: "Wallasey", county: "Merseyside", type: "borough"},
{name: "Wallingford", county: "Oxfordshire", type: "town"},
{name: "Wallington", county: "Greater London", type: "borough"},
{name: "Wallsend", county: "Tyne and Wear", type: "borough"},
{name: "Walsall", county: "West Midlands", type: "borough"},
{name: "Waltham Abbey", county: "Essex", type: "town"},
{name: "Waltham Cross", county: "Hertfordshire", type: "market charter"},
{name: "Walthamstow", county: "Greater London", type: "borough"},
{name: "Walton-on-Thames", county: "Surrey", type: "market charter"},
{name: "Wantage", county: "Oxfordshire", type: "town"},
{name: "Ware", county: "Hertfordshire", type: "town"},
{name: "Wareham", county: "Dorset", type: "town"},
{name: "Warminster", county: "Wiltshire", type: "town"},
{name: "Warrington", county: "Cheshire", type: "borough"},
{name: "Warwick", county: "Warwickshire", type: "town"},
{name: "Watchet", county: "Somerset", type: "town"},
{name: "Watford", county: "Hertfordshire", type: "borough"},
{name: "Wath-upon-Dearne", county: "South Yorkshire", type: "market charter"},
{name: "Watlington", county: "Oxfordshire", type: "market charter"},
{name: "Watton", county: "Norfolk", type: "town"},
{name: "Wellingborough", county: "Northamptonshire", type: "market charter"},
{name: "Wednesbury", county: "West Midlands", type: "borough (1886 - 1966)"},
{name: "Wellington", county: "Shropshire", type: "town"},
{name: "Wellington", county: "Somerset", type: "town"},
{name: "Wells-next-the-Sea", county: "Norfolk", type: "town"},
{name: "Wem", county: "Shropshire", type: "town"},
{name: "Wembley", county: "Greater London", type: "borough"},
{name: "Wendover", county: "Buckinghamshire", type: "market charter"},
{name: "West Bedlington", county: "Northumberland", type: "town"},
{name: "West Bromwich", county: "West Midlands", type: "borough"},
{name: "West Ham", county: "Greater London", type: "borough"},
{name: "West Malling", county: "Kent", type: "market charter"},
{name: "West Mersea", county: "Essex", type: "town"},
{name: "West Tilbury", county: "Essex", type: "market charter"},
{name: "Westbury", county: "Wiltshire", type: "town"},
{name: "Westerham", county: "Kent", type: "market charter"},
{name: "Westhoughton", county: "Greater Manchester", type: "town"},
{name: "Weston-super-Mare", county: "Somerset", type: "town"},
{name: "Wetherby", county: "West Yorkshire", type: "town"},
{name: "Weybridge", county: "Surrey", type: "market charter"},
{name: "Weymouth", county: "Dorset", type: "town"},
{name: "Whaley Bridge", county: "Derbyshire", type: "town"},
{name: "Whitby", county: "North Yorkshire", type: "town"},
{name: "Whitchurch", county: "Hampshire", type: "town"},
{name: "Whitchurch", county: "Shropshire", type: "town"},
{name: "Whitehaven", county: "Cumbria", type: "borough"},
{name: "Whitehill", county: "Hampshire", type: "town"},
{name: "Whitnash", county: "Warwickshire", type: "town"},
{name: "Whittlesey", county: "Cambridgeshire", type: "town"},
{name: "Whitworth", county: "Lancashire", type: "town"},
{name: "Wickham", county: "Hampshire", type: "market charter"},
{name: "Wickwar", county: "Gloucestershire", type: "market charter"},
{name: "Widnes", county: "Cheshire", type: "borough"},
{name: "Wigan", county: "Greater Manchester", type: "borough"},
{name: "Wigton", county: "Cumbria", type: "town"},
{name: "Willenhall", county: "West Midlands", type: "market charter"},
{name: "Willesden", county: "Greater London", type: "borough"},
{name: "Wilton", county: "Wiltshire", type: "town"},
{name: "Wilmslow", county: "Cheshire", type: "town"},
{name: "Wimbledon", county: "Greater London", type: "borough"},
{name: "Wimborne Minster", county: "Dorset", type: "town"},
{name: "Wincanton", county: "Somerset", type: "town"},
{name: "Winchcombe", county: "Gloucestershire", type: "town"},
{name: "Winchelsea", county: "East Sussex", type: "market charter"},
{name: "Windermere", county: "Cumbria", type: "town"},
{name: "Windsor", county: "Berkshire", type: "borough"},
{name: "Winsford", county: "Cheshire", type: "town"},
{name: "Winslow", county: "Buckinghamshire", type: "town"},
{name: "Winterton", county: "Lincolnshire", type: "town"},
{name: "Wirksworth", county: "Derbyshire", type: "town"},
{name: "Wisbech", county: "Cambridgeshire", type: "town"},
{name: "Witham", county: "Essex", type: "town"},
{name: "Withernsea", county: "East Riding of Yorkshire", type: "town"},
{name: "Witney", county: "Oxfordshire", type: "town"},
{name: "Wiveliscombe", county: "Somerset", type: "town"},
{name: "Wivenhoe", county: "Essex", type: "town"},
{name: "Woburn", county: "Bedfordshire", type: "market charter"},
{name: "Woburn Sands", county: "Buckinghamshire", type: "town"},
{name: "Woking", county: "Surrey", type: "market charter"},
{name: "Wokingham", county: "Berkshire", type: "town"},
{name: "Wolsingham", county: "Durham", type: "market charter"},
{name: "Wolverton and Greenleys", county: "Buckinghamshire", type: "town"},
{name: "Wood Green", county: "Greater London", type: "borough"},
{name: "Woodford", county: "Greater London", type: "borough"},
{name: "Woodbridge", county: "Suffolk", type: "town"},
{name: "Woodley", county: "Berkshire", type: "town"},
{name: "Woodstock", county: "Oxfordshire", type: "town"},
{name: "Wooler", county: "Northumberland", type: "market charter"},
{name: "Workington", county: "Cumbria", type: "town"},
{name: "Worksop", county: "Nottinghamshire", type: "charter trustees"},
{name: "Worthing", county: "West Sussex", type: "borough"},
{name: "Wotton-under-Edge", county: "Gloucestershire", type: "town"},
{name: "Wragby", county: "Lincolnshire", type: "town"},
{name: "Wymondham", county: "Norfolk", type: "town"},
{name: "Yarm", county: "North Yorkshire", type: "town"},
{name: "Yarmouth", county: "Isle of Wight", type: "town"},
{name: "Yate", county: "Gloucestershire", type: "town"},
{name: "Yateley", county: "Hampshire", type: "town"},
{name: "Yeovil", county: "Somerset", type: "town"},
];
